/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlogsRouteRouteImport } from './routes/_blogs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsPublicationsIndexRouteImport } from './routes/_blogs/publications/index'
import { Route as BlogsOngoingIndexRouteImport } from './routes/_blogs/ongoing/index'

const BlogsRouteRoute = BlogsRouteRouteImport.update({
  id: '/_blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsPublicationsIndexRoute = BlogsPublicationsIndexRouteImport.update({
  id: '/publications/',
  path: '/publications/',
  getParentRoute: () => BlogsRouteRoute,
} as any)
const BlogsOngoingIndexRoute = BlogsOngoingIndexRouteImport.update({
  id: '/ongoing/',
  path: '/ongoing/',
  getParentRoute: () => BlogsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ongoing': typeof BlogsOngoingIndexRoute
  '/publications': typeof BlogsPublicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ongoing': typeof BlogsOngoingIndexRoute
  '/publications': typeof BlogsPublicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_blogs': typeof BlogsRouteRouteWithChildren
  '/_blogs/ongoing/': typeof BlogsOngoingIndexRoute
  '/_blogs/publications/': typeof BlogsPublicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ongoing' | '/publications'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ongoing' | '/publications'
  id:
    | '__root__'
    | '/'
    | '/_blogs'
    | '/_blogs/ongoing/'
    | '/_blogs/publications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogsRouteRoute: typeof BlogsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_blogs': {
      id: '/_blogs'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BlogsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_blogs/publications/': {
      id: '/_blogs/publications/'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof BlogsPublicationsIndexRouteImport
      parentRoute: typeof BlogsRouteRoute
    }
    '/_blogs/ongoing/': {
      id: '/_blogs/ongoing/'
      path: '/ongoing'
      fullPath: '/ongoing'
      preLoaderRoute: typeof BlogsOngoingIndexRouteImport
      parentRoute: typeof BlogsRouteRoute
    }
  }
}

interface BlogsRouteRouteChildren {
  BlogsOngoingIndexRoute: typeof BlogsOngoingIndexRoute
  BlogsPublicationsIndexRoute: typeof BlogsPublicationsIndexRoute
}

const BlogsRouteRouteChildren: BlogsRouteRouteChildren = {
  BlogsOngoingIndexRoute: BlogsOngoingIndexRoute,
  BlogsPublicationsIndexRoute: BlogsPublicationsIndexRoute,
}

const BlogsRouteRouteWithChildren = BlogsRouteRoute._addFileChildren(
  BlogsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogsRouteRoute: BlogsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
